import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { api } from '../api/client'
const initial={transcript:false,patient_summary:false,medications:false,warnings:false,translation:false}
export default function AssistantReview(){
 const{reviewId}=useParams();const nav=useNavigate();const[review,setReview]=useState(null);const[c,setC]=useState(null);const[checks,setChecks]=useState(initial);const[checked,setChecked]=useState(false);const[notes,setNotes]=useState('');const[err,setErr]=useState(null);const[busy,setBusy]=useState(false)
 useEffect(()=>{Promise.all([api.assistantReview(reviewId),api.assistantReviewCase(reviewId)]).then(([r,c])=>{setReview(r);setC(c)}).catch(e=>setErr(e.message))},[reviewId])
 async function submit(){setBusy(true);setErr(null);try{await api.submitAssistantReview(reviewId,{checked,notes,checklist:checks});nav('/assistant')}catch(e){setErr(e.message)}finally{setBusy(false)}}
 if(err)return <main className="page"><div className="error panel">{err}</div></main>;if(!c||!review)return <main className="page"><div className="loading-card">Loading assigned case…</div></main>
 const all=Object.values(checks).every(Boolean);const meds=c.medication_rows?.length?c.medication_rows:(c.structured_data?.medications||[]);const rtl=['ur','pa_shah','ar','ps','sd'].includes(c.patient_language)
 return <main className="page"><div className="breadcrumb"><Link to="/assistant">Assistant review</Link><span>›</span><span>Consultation #{c.consultation_id}</span></div><section className="case-header"><div><span className="eyebrow">ASSIGNED CASE · READ / CHECK ONLY</span><h1>Pre-release assistant review</h1><p>The treating doctor remains the final approver and release authority.</p></div><span className="pill warn-pill">assistant pre-review</span></section>
 <div className="scope-banner"><strong>Your role boundary</strong><span>You can inspect the assigned transcript, patient explanation, medication fields and automated warnings. You cannot edit the clinical source, diagnose, prescribe, approve, release or cross-check the case.</span></div>
 <section className="grid-2"><div className="card"><h2>Source transcript</h2><textarea readOnly className={`tall ${rtl?'rtl':''}`} value={c.verified_transcript||c.raw_transcript||''}/></div><div className="card"><h2>Patient explanation</h2><textarea readOnly className="tall" value={c.doctor_edited_summary||c.patient_summary_en||''}/>{c.patient_summary_translated&&c.patient_language!=='en'&&<><h3>Translated version</h3><div className={`translation-box ${rtl?'rtl':''}`}><p>{c.patient_summary_translated}</p></div></>}</div></section>
 <section className="grid-2"><div className="card"><h2>Automated review signals</h2>{!c.safety_checks?.length?<div className="muted">No recorded safety checks.</div>:<div className="signal-list">{c.safety_checks.map(x=><div className={`signal-row ${x.resolved?'resolved':''}`} key={x.id}><div><strong>{x.check_type.replaceAll('_',' ')}</strong><span>{x.status}{x.severity?` · ${x.severity}`:''}</span></div><p>{x.statement||'No additional statement'}</p><small>{x.resolved?'Already resolved in the original doctor safety workflow':'Visible for the treating doctor to resolve before approval if required'}</small></div>)}</div>}</div><div className="card"><h2>Medication information</h2>{!meds.length?<div className="muted">No extracted medication rows.</div>:<div className="medication-patient-list">{meds.map((m,i)=><div className="medication-patient-card" key={i}><div className="medication-patient-head"><strong>{m.canonical_name||m.name||m.name_as_heard||'Medication'}</strong><span className="dose-chip">{[m.dose,m.strength].filter(Boolean).join(' · ')||'Dose not stated'}</span></div><div className="medication-detail-grid"><div><span>Frequency</span><strong>{m.frequency||'—'}</strong></div><div><span>Timing</span><strong>{m.timing||m.food_instruction||'—'}</strong></div><div><span>Duration</span><strong>{m.duration||'—'}</strong></div></div></div>)}</div>}</div></section>
 <section className="card checklist-card"><span className="eyebrow">REQUIRED CHECKLIST</span><h2>Confirm what you checked</h2><p>Tick each item only after inspecting the visible source. Concerns should be written in the notes for the doctor.</p><div className="check-grid">{[['transcript','I checked the transcript/source information'],['patient_summary','I checked the patient-facing explanation'],['medications','I checked medicine names, dose/frequency/duration shown'],['warnings','I inspected the visible automated warnings'],['translation','I checked the translation where applicable (or confirmed English-only)']].map(([k,label])=><label className={`check-card ${checks[k]?'checked':''}`} key={k}><input type="checkbox" checked={checks[k]} onChange={e=>setChecks({...checks,[k]:e.target.checked})}/><span>{label}</span></label>)}</div><label>Notes for the treating doctor</label><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Describe anything the doctor should re-check…"/><label className={`final-check ${checked?'checked':''}`}><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/><span><strong>I have checked this case</strong><small>This returns the case to the treating doctor and does not release it to the patient.</small></span></label>{err&&<div className="error">{err}</div>}<button className="wide" disabled={busy||!all||!checked} onClick={submit}>Return reviewed case to doctor</button></section></main>
}
